### ISSUE TITLE
Not compatible with PHP 8 due to dependencies

### ISSUE THREAD

**Issue by NathanDayFE** [ctidigital/magento2-configurator#127]
Whilst this module in itself doesn't specify any PHP requirements and the code is compatible with PHP 8, the dependency on `"firegento/fastsimpleimport": "1.3.4"` makes this module also not compatible. Firegento have resolved the PHP compatibility in version 2+ but the exact versioning used here makes it not possible to update that module individually.

Error:
during `bin/magento setup:di:compile`
![image](https://user-images.githubusercontent.com/68845089/203273854-2f6c6929-9cd3-423e-907b-49caa8c4da74.png)

Resolution:
modify the composer requirement for `firegento/fastsimpleimport` to either not specify a version, or so that version 2+ can be installed

**Comment by paulpartington-cti** [comment]
#128 has been merged into 3.2.0. Thank you.
