### ISSUE TITLE
Errors with Magento 2.1.6 EE

### ISSUE THREAD

**Issue by chamalC** [ctidigital/magento2-configurator#26]
I have setup the configuration with magento 2.1.6 EE. But when I run products component in the examples folder I'm getting an error for configurable.csv. "Invalid option value in row(s): 1". 

and when runs websites component it returns an error 
" Circular dependency: Magento\Backend\Model\Auth\Session depends on Magento\Backend\Model\Authorization\RoleLocator and vice versa.    "

**Comment by iancassidyweb** [comment]
Hi @chamalC I believe you found a solution to this issue? 

Can you let me know what the workaround was so we can update our documentation. 

Ian
