### ISSUE TITLE
Feature: SQL

### ISSUE THREAD

**Issue by furan917** [ctidigital/magento2-configurator#32]
What is the purpose of this feature meant to be? I keep looking at it and but I'm not getting if it is meant to be data upgrades or something else?

It wont be something I work on if I get time but for others who may see this, or someone I may be able to suggest to work on it I'd like to know how best to describe this section.

**Comment by chevli** [comment]
Hi @furan917,

This is simply to run any arbitrary SQL queries to populate data which may not possible via a Model. We build this as part of M1 Configurator.
For example
- https://github.com/ctidigital/magento-configurator/blob/master/src/app/code/community/Cti/Configurator/Helper/Components/Sql.php
- https://github.com/ctidigital/magento-configurator/blob/master/samples/components/sql/sitemap.sql.

We have also found this useful for internal projects which have third party modules with model based data where it's not worth putting in the effort for creating a component for their models. These can be things like shipping rates on third party modules to aid development.

We will eventually get around to doing this once we require this functionality on the next project of ours.

Thank you
