### ISSUE TITLE
Master YAML does not exist. Please create one in /var/www/html/app/etc/master.yaml in magento 2.1.8

### ISSUE THREAD

**Issue by Gujarats** [ctidigital/magento2-configurator#43]
I have copied the master.yml in the sample to my `app/etc/master.yml`. But when I run this command `magento configurator --env=local` I got this error : 

```shell
Master YAML does not exist. Please create one in /var/www/html/app/etc/master.yaml
```

it is weird error even though the file is exist in `app/etc`  any idea ?

**Comment by chevli** [comment]
Hi @Gujarats,

I believe you have a typo in the file extension. This should be .yaml as oppose to .yml.

I hope that helps.

Thanks

**Comment by Gujarats** [comment]
@chevli 
oh yes this is my bad, thanks for pointing it out.

Cheers
