### ISSUE TITLE
Remove magento/framework requirement from composer.json

### ISSUE THREAD

**Issue by chevli** [ctidigital/magento2-configurator#51]
As we have already have ```"type":"magento2-module"``` in the composer.json, ```magento/framework``` should not be required.
https://github.com/ctidigital/magento2-configurator/blob/d0eabed2b0b88f3bf9718a72f997e155bc802c1d/composer.json#L14

**Comment by dank00** [comment]
heres the failing travis build:

https://travis-ci.org/ctidigital/magento2-configurator/jobs/296733551

**Comment by chevli** [comment]
Hi @dank00,

Yes, the magento/framework was still required as part of some of the tests so this had to be included via travis in order for it to progress with the test.

This is merged in now.

Thank you :)
