### ISSUE TITLE
Running configurator from outside web root

### ISSUE THREAD

**Issue by iancassidyweb** [ctidigital/magento2-configurator#8]
When running the configurator command from outside the web root you receive the following error:

`file_get_contents(app/etc/configurator/local/config.yaml): failed to open stream: No such file or directory`

The Exception is thrown by the YamlComponentAbstract class which contains two methods:

**Can Parse Method**

This method prepends the Magento web root before pulling in the sources from master.yaml
[source](https://github.com/ctidigital/magento2-configurator/blob/develop/Model/Component/YamlComponentAbstract.php#L22)

**Parse Data Method**

This method does not prepend the Magento web root before executing file_get_contents which is what causes the error.
[source](https://github.com/ctidigital/magento2-configurator/blob/develop/Model/Component/YamlComponentAbstract.php#L48)

**Proposed Solution**

The Parse Data Method needs to prepend the Magento web root before running file_get_contents

**Comment by robjstanley** [comment]
Resolved in commit https://github.com/ctidigital/magento2-configurator/commit/65ac555f578784837d0377e538860cd25af96cbb
