### ISSUE TITLE
composer conflict on magento 2.2.5

### ISSUE THREAD

**Issue by rafashkembi** [ctidigital/magento2-configurator#83]
I have a fresh install of magento 2.2.5 and i tried to install ctidigital/magento2-configurator

This is my log of the process 

> composer require ctidigital/magento2-configurator --ignore-platform-reqs
> Using version ^1.4 for ctidigital/magento2-configurator
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: don't install ctidigital/magento2-configurator 1.4.1
>     - Conclusion: remove symfony/console v2.8.42
>     - Conclusion: don't install symfony/console v2.8.42
>     - symfony/yaml v3.4.0 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.1 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.10 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.11 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.12 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.2 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.3 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.4 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.5 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.6 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.7 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.8 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v3.4.9 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.0 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.1 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.10 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.11 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.12 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.2 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.3 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.4 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.5 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.6 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.7 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.8 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.0.9 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.1.0 conflicts with symfony/console[v2.8.42].
>     - symfony/yaml v4.1.1 conflicts with symfony/console[v2.8.42].
>     - Conclusion: don't install symfony/dependency-injection v4.1.1|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.10|install symfony/yaml v3.4.11|install symfony/yaml v3.4.12|install symfony/yaml v3.4.2|install symfony/yaml v3.4.3|install symfony/yaml v3.4.4|install symfony/yaml v3.4.5|install symfony/yaml v3.4.6|install symfony/yaml v3.4.7|install symfony/yaml v3.4.8|install symfony/yaml v3.4.9|install symfony/yaml v4.0.0|install symfony/yaml v4.0.1|install symfony/yaml v4.0.10|install symfony/yaml v4.0.11|install symfony/yaml v4.0.12|install symfony/yaml v4.0.2|install symfony/yaml v4.0.3|install symfony/yaml v4.0.4|install symfony/yaml v4.0.5|install symfony/yaml v4.0.6|install symfony/yaml v4.0.7|install symfony/yaml v4.0.8|install symfony/yaml v4.0.9|install symfony/yaml v4.1.0|install symfony/yaml v4.1.1
>     - Conclusion: don't install ctidigital/magento2-configurator 1.4.1|remove symfony/dependency-injection v4.1.1|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.10|install symfony/yaml v3.4.11|install symfony/yaml v3.4.12|install symfony/yaml v3.4.2|install symfony/yaml v3.4.3|install symfony/yaml v3.4.4|install symfony/yaml v3.4.5|install symfony/yaml v3.4.6|install symfony/yaml v3.4.7|install symfony/yaml v3.4.8|install symfony/yaml v3.4.9|install symfony/yaml v4.0.0|install symfony/yaml v4.0.1|install symfony/yaml v4.0.10|install symfony/yaml v4.0.11|install symfony/yaml v4.0.12|install symfony/yaml v4.0.2|install symfony/yaml v4.0.3|install symfony/yaml v4.0.4|install symfony/yaml v4.0.5|install symfony/yaml v4.0.6|install symfony/yaml v4.0.7|install symfony/yaml v4.0.8|install symfony/yaml v4.0.9|install symfony/yaml v4.1.0|install symfony/yaml v4.1.1
>     - Conclusion: don't install ctidigital/magento2-configurator 1.4.1|don't install symfony/dependency-injection v4.1.1|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.10|install symfony/yaml v3.4.11|install symfony/yaml v3.4.12|install symfony/yaml v3.4.2|install symfony/yaml v3.4.3|install symfony/yaml v3.4.4|install symfony/yaml v3.4.5|install symfony/yaml v3.4.6|install symfony/yaml v3.4.7|install symfony/yaml v3.4.8|install symfony/yaml v3.4.9|install symfony/yaml v4.0.0|install symfony/yaml v4.0.1|install symfony/yaml v4.0.10|install symfony/yaml v4.0.11|install symfony/yaml v4.0.12|install symfony/yaml v4.0.2|install symfony/yaml v4.0.3|install symfony/yaml v4.0.4|install symfony/yaml v4.0.5|install symfony/yaml v4.0.6|install symfony/yaml v4.0.7|install symfony/yaml v4.0.8|install symfony/yaml v4.0.9|install symfony/yaml v4.1.0|install symfony/yaml v4.1.1
>     - Installation request for symfony/console (locked at v2.8.42) -> satisfiable by symfony/console[v2.8.42].
>     - Conclusion: don't install ctidigital/magento2-configurator 1.4.1|remove symfony/dependency-injection v4.1.1|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.10|install symfony/yaml v3.4.11|install symfony/yaml v3.4.12|install symfony/yaml v3.4.2|install symfony/yaml v3.4.3|install symfony/yaml v3.4.4|install symfony/yaml v3.4.5|install symfony/yaml v3.4.6|install symfony/yaml v3.4.7|install symfony/yaml v3.4.8|install symfony/yaml v3.4.9|install symfony/yaml v4.0.0|install symfony/yaml v4.0.1|install symfony/yaml v4.0.10|install symfony/yaml v4.0.11|install symfony/yaml v4.0.12|install symfony/yaml v4.0.2|install symfony/yaml v4.0.3|install symfony/yaml v4.0.4|install symfony/yaml v4.0.5|install symfony/yaml v4.0.6|install symfony/yaml v4.0.7|install symfony/yaml v4.0.8|install symfony/yaml v4.0.9|install symfony/yaml v4.1.0|install symfony/yaml v4.1.1
>     - Conclusion: don't install ctidigital/magento2-configurator 1.4.1|don't install symfony/dependency-injection v4.1.1|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.10|install symfony/yaml v3.4.11|install symfony/yaml v3.4.12|install symfony/yaml v3.4.2|install symfony/yaml v3.4.3|install symfony/yaml v3.4.4|install symfony/yaml v3.4.5|install symfony/yaml v3.4.6|install symfony/yaml v3.4.7|install symfony/yaml v3.4.8|install symfony/yaml v3.4.9|install symfony/yaml v4.0.0|install symfony/yaml v4.0.1|install symfony/yaml v4.0.10|install symfony/yaml v4.0.11|install symfony/yaml v4.0.12|install symfony/yaml v4.0.2|install symfony/yaml v4.0.3|install symfony/yaml v4.0.4|install symfony/yaml v4.0.5|install symfony/yaml v4.0.6|install symfony/yaml v4.0.7|install symfony/yaml v4.0.8|install symfony/yaml v4.0.9|install symfony/yaml v4.1.0|install symfony/yaml v4.1.1
>     - Installation request for ctidigital/magento2-configurator ^1.4 -> satisfiable by ctidigital/magento2-configurator[1.4.0, 1.4.1].
>     - Conclusion: remove symfony/dependency-injection v4.1.1|install symfony/yaml v3.4.0|install symfony/yaml v3.4.1|install symfony/yaml v3.4.10|install symfony/yaml v3.4.11|install symfony/yaml v3.4.12|install symfony/yaml v3.4.2|install symfony/yaml v3.4.3|install symfony/yaml v3.4.4|install symfony/yaml v3.4.5|install symfony/yaml v3.4.6|install symfony/yaml v3.4.7|install symfony/yaml v3.4.8|install symfony/yaml v3.4.9|install symfony/yaml v4.0.0|install symfony/yaml v4.0.1|install symfony/yaml v4.0.10|install symfony/yaml v4.0.11|install symfony/yaml v4.0.12|install symfony/yaml v4.0.2|install symfony/yaml v4.0.3|install symfony/yaml v4.0.4|install symfony/yaml v4.0.5|install symfony/yaml v4.0.6|install symfony/yaml v4.0.7|install symfony/yaml v4.0.8|install symfony/yaml v4.0.9|install symfony/yaml v4.1.0|install symfony/yaml v4.1.1
>     - ctidigital/magento2-configurator 1.4.0 requires symfony/yaml >2.8.0 -> satisfiable by symfony/yaml[v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v2.8.28, v2.8.29, v2.8.3, v2.8.30, v2.8.31, v2.8.32, v2.8.33, v2.8.34, v2.8.35, v2.8.36, v2.8.37, v2.8.38, v2.8.39, v2.8.4, v2.8.40, v2.8.41, v2.8.42, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9, v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9, v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9, v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1].
>     - symfony/yaml v2.8.1 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.10 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.11 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.12 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.13 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.14 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.15 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.16 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.17 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.18 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.19 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.2 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.20 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.21 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.22 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.23 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.24 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.25 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.26 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.27 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.28 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.29 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.3 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.30 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.31 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.32 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.33 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.34 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.35 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.36 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.37 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.38 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.39 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.4 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.40 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.41 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.42 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.5 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.6 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.7 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.8 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v2.8.9 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.0 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.1 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.2 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.3 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.4 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.5 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.6 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.7 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.8 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.0.9 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.0 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.1 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.10 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.2 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.3 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.4 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.5 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.6 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.7 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.8 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.1.9 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.0 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.1 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.10 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.11 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.12 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.13 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.14 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.2 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.3 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.4 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.5 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.6 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.7 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.8 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.2.9 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.0 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.1 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.10 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.11 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.12 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.13 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.14 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.15 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.16 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.17 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.2 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.3 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.4 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.5 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.6 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.7 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.8 conflicts with symfony/dependency-injection[v4.1.1].
>     - symfony/yaml v3.3.9 conflicts with symfony/dependency-injection[v4.1.1].
>     - Installation request for symfony/dependency-injection (locked at v4.1.1) -> satisfiable by symfony/dependency-injection[v4.1.1].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

My composer.json file is as follows.

> {
>     "name": "magento/project-community-edition",
>     "description": "eCommerce Platform for Growth (Community Edition)",
>     "type": "project",
>     "version": "2.2.5",
>     "license": [
>         "OSL-3.0",
>         "AFL-3.0"
>     ],
>     "require": {
>         "magento/product-community-edition": "2.2.5",
>         "composer/composer": "@alpha"
>     },
>     "require-dev": {
>         "phpunit/phpunit": "~6.2.0",
>         "squizlabs/php_codesniffer": "3.2.2",
>         "phpmd/phpmd": "@stable",
>         "pdepend/pdepend": "2.5.2",
>         "friendsofphp/php-cs-fixer": "~2.2.1",
>         "lusitanian/oauth": "~0.8.10",
>         "sebastian/phpcpd": "2.0.4"
>     },
>     "autoload": {
>         "psr-4": {
>             "Magento\\Framework\\": "lib/internal/Magento/Framework/",
>             "Magento\\Setup\\": "setup/src/Magento/Setup/",
>             "Magento\\": "app/code/Magento/"
>         },
>         "psr-0": {
>             "": [
>                 "app/code/"
>             ]
>         },
>         "files": [
>             "app/etc/NonComposerComponentRegistration.php"
>         ],
>         "exclude-from-classmap": [
>             "**/dev/**",
>             "**/update/**",
>             "**/Test/**"
>         ]
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
>             "Magento\\Tools\\": "dev/tools/Magento/Tools/",
>             "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
>             "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
>             "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
>         }
>     },
>     "minimum-stability": "stable",
>     "repositories": [
>         {
>             "type": "composer",
>             "url": "https://repo.magento.com/"
>         }
>     ],
>     "extra": {
>         "magento-force": "override"
>     }
> }

**Comment by chevli** [comment]
Hi @rafashkembi,

Currently we're still working on 2.2.x compatible version of the configurator.
Please use https://github.com/ctidigital/magento2-configurator/tree/2.2-alpha in the meantime as we look to stabilise and refactor the PHP Unit tests.

Thank you
