### ISSUE TITLE
Add flag to gracefully continue if source .yaml files don't exist

### ISSUE THREAD

**Issue by rick-cti** [ctidigital/magento2-configurator#84]
Currently, if a .yaml file defined in `master.yaml` does not exist, the `configurator:run` command fails with an error message:

`Could not find file in path /path/to/my/file.yaml`

Is it possible to add a command line flag (such as '`-i`', or '`--ignore-missing-files`') so that `configurator:run` just outputs a message to say it's skipping the missing file in this scenario, then proceeds with the rest?

**Comment by paulpartington-cti** [comment]
@rick-cti I've put a change in the next release of Configurator to add this feature.

**Comment by paulpartington-cti** [comment]
@rick-cti This has been included in 3.0.0.
